require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'GrapeVineAI' do
  config = use_native_modules!
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'

  use_react_native!(:path => config["reactNativePath"])

  target 'GrapeVineAITests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({
               'Flipper' => '0.80.0'
               })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'GrapeVineAI-tvOS' do
  # Pods for GrapeVineAI-tvOS

  target 'GrapeVineAI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
